# Generated by Django 2.1.1 on 2018-11-20 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_auto_20181120_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='present',
        ),
        migrations.RemoveField(
            model_name='order',
            name='present_num',
        ),
        migrations.AddField(
            model_name='orderitemu',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Order'),
        ),
        migrations.AddField(
            model_name='orderitemu',
            name='present',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Present'),
        ),
    ]
