# Generated by Django 2.1.1 on 2018-11-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_auto_20181120_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('index', models.IntegerField()),
            ],
        ),
    ]
