# Generated by Django 2.1.1 on 2018-11-20 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_crousel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='tag',
            new_name='categoryP',
        ),
    ]
