# Generated by Django 2.1.1 on 2018-11-20 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_auto_20181120_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('present', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Present')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.User')),
            ],
        ),
    ]
