# Generated by Django 2.1.1 on 2018-11-27 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationshipc',
            old_name='ref',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='relationshipt',
            old_name='ref',
            new_name='tag',
        ),
    ]
