# Generated by Django 2.1.1 on 2018-11-27 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_auto_20181127_1825'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RelationshipC',
            new_name='Rec',
        ),
        migrations.RenameModel(
            old_name='RelationshipT',
            new_name='Ret',
        ),
    ]
