# Generated by Django 2.1.1 on 2018-11-27 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0011_auto_20181127_1837'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItemU',
            new_name='Oru',
        ),
    ]
